// Sample data for the prototype. Fabricated — no real customer records.
//
// Built off-subscription through the local model gateway (Lane B) and checked by a
// schema validator that every record had to pass before it was accepted here:
// Admin first and Accounts last on every route, client-supplied artwork never sitting
// in the approval queue, deposits never above the total, +267 numbers throughout.
//
// Each record carries how far along its route the job has got, so the seeded day
// looks like a real morning: some jobs booked in, some on the machines, some waiting
// on a customer to approve a proof, a few already late.

import { buildStages, type Order, type Stage } from "./domain";

interface Seed extends Omit<Order, "createdAt" | "dueAt" | "stages" | "delivery" | "collectedAt"> {
  dueInHours: number;
  done: number;      // stages finished
  working: boolean;  // the next stage is on somebody's bench right now
  delivery: Order["delivery"];
}

const RAW: Seed[] = [
  { id: "JC-2609-121", odooRef: "SO-2026-1047", odooSynced: true, customer: "Mogoditshane Junior Secondary School", contact: "+267 73548219", email: "admin@mogoditshanejss.co.bw", type: "banners", description: "PVC open day banners 3m x 1m with eyelets", qty: 6, route: ["admin", "design", "sewing", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 28, priority: "standard", total: 2880, deposit: 1440, fulfilment: "delivery", address: "Block 8, Gaborone", delivery: "not_started", notes: "Deliver to reception before lunch.", done: 3, working: false },
  { id: "JC-2609-126", odooRef: "SO-2026-1053", odooSynced: true, customer: "Tlokweng United Football Club", contact: "+267 71290644", email: "secretary@tlokwengunitedfc.co.bw", type: "banners", description: "Match day fence banners 2m x 1m", qty: 12, route: ["admin", "sewing", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: -6, priority: "rush", total: 4200, deposit: 4200, fulfilment: "collection", delivery: "not_started", notes: "Coach waiting; prioritise hemming and eyelets.", done: 1, working: false },
  { id: "JC-2609-133", odooRef: "SO-2026-1061", odooSynced: true, customer: "Kgale View Funeral Parlour", contact: "+267 74731852", email: "orders@kgaleviewfunerals.co.bw", type: "banners", description: "Funeral service direction banners A-frame size", qty: 8, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "pending", revisionsUsed: 0, dueInHours: 18, priority: "rush", total: 2560, deposit: 0, fulfilment: "delivery", address: "Plot 14458, Gaborone West Industrial", delivery: "not_started", notes: "Confirm names before final production.", done: 2, working: false },
  { id: "JC-2609-139", odooRef: "SO-2026-1074", odooSynced: true, customer: "Mma Thato Hair Studio", contact: "+267 76854027", email: "bookings@mmathatohair.co.bw", type: "banners", description: "Salon promotion pull-up banners 850mm x 2m", qty: 3, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "changes_requested", revisionsUsed: 2, dueInHours: 72, priority: "standard", total: 1950, deposit: 975, fulfilment: "collection", delivery: "not_started", notes: "Client wants brighter pink on price panel.", done: 1, working: true },
  { id: "JC-2609-201", odooRef: "SO-2026-1047", odooSynced: true, customer: "Mogoditshane Fighters Football Club", contact: "+267 71648209", email: "orders@mogoditshanefighters.co.bw", type: "branded_uniforms", description: "embroidered tracksuit tops with club crest", qty: 42, route: ["admin", "design", "embroidery", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 18, priority: "rush", total: 15120, deposit: 7560, fulfilment: "collection", delivery: "not_started", notes: "Coach to confirm sizes before stitching starts.", done: 3, working: false },
  { id: "JC-2609-206", odooRef: "SO-2026-1053", odooSynced: true, customer: "Naledi Motors Tuckshop", contact: "+267 74291583", email: "naledituckshop@gmail.com", type: "branded_uniforms", description: "dtf logo golf shirts for staff", qty: 12, route: ["admin", "dtf", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: -6, priority: "rush", total: 2160, deposit: 0, fulfilment: "collection", delivery: "not_started", notes: "Customer waiting; print white logos on navy shirts.", done: 2, working: false },
  { id: "JC-2609-214", odooRef: "SO-2026-1061", odooSynced: true, customer: "Bonnington Junior Secondary School", contact: "+267 73902841", email: "procurement@bonningtonjss.ac.bw", type: "branded_uniforms", description: "sublimated sports bibs with house names", qty: 180, route: ["admin", "design", "sublimation", "sewing", "accounts"], artwork: "in_house", approval: "pending", revisionsUsed: 2, dueInHours: 72, priority: "standard", total: 25200, deposit: 12600, fulfilment: "delivery", address: "Block 7, Gaborone", delivery: "not_started", notes: "Separate packs by red, blue, green and yellow houses.", done: 2, working: false },
  { id: "JC-2609-219", odooRef: "SO-2026-1074", odooSynced: true, customer: "Mmokolodi View Lodge", contact: "+267 76220475", email: "uniforms@mmokolodiviewlodge.co.bw", type: "branded_uniforms", description: "embroidered chef jackets and aprons", qty: 28, route: ["admin", "embroidery", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: 44, priority: "standard", total: 12600, deposit: 12600, fulfilment: "delivery", address: "Plot 35047, Phakalane, Gaborone", delivery: "packed", notes: "Deliver to reception before evening shift.", done: 3, working: false },
  { id: "JC-2609-181", odooRef: "SO-2026-1042", odooSynced: true, customer: "Mogoditshane Fighters FC", contact: "+267 71234567", email: "orders@mogoditshanefightersfc.co.bw", type: "dtf_transfers", description: "A4 crest and sponsor transfers for jerseys", qty: 85, route: ["admin", "dtf", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: 18, priority: "standard", total: 2975, deposit: 1500, fulfilment: "collection", delivery: "not_started", notes: "Coach collecting before evening training.", done: 1, working: true },
  { id: "JC-2609-184", odooRef: "SO-2026-1057", odooSynced: true, customer: "Little Stars Pre-School", contact: "+267 73451890", email: "admin@littlestars-preschool.co.bw", type: "dtf_transfers", description: "Small name label transfers for tracksuits", qty: 240, route: ["admin", "design", "dtf", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 72, priority: "standard", total: 3600, deposit: 1800, fulfilment: "delivery", address: "Plot 30876, Block 8, Gaborone", delivery: "not_started", notes: "Pack by class list supplied on email.", done: 3, working: false },
  { id: "JC-2609-192", odooRef: "SO-2026-1083", odooSynced: true, customer: "Phakalane Serenity Lodge", contact: "+267 76220944", email: "reservations@phakalaneserenitylodge.co.bw", type: "dtf_transfers", description: "Left chest logo transfers for staff polos", qty: 60, route: ["admin", "design", "dtf", "accounts"], artwork: "in_house", approval: "changes_requested", revisionsUsed: 2, dueInHours: -6, priority: "rush", total: 1800, deposit: 0, fulfilment: "delivery", address: "Plot 61238, Phakalane, Gaborone", delivery: "not_started", notes: "Waiting for final logo colour confirmation.", done: 1, working: true },
  { id: "JC-2609-198", odooRef: "SO-2026-1096", odooSynced: true, customer: "Naledi Hair Studio", contact: "+267 77185602", email: "bookings@naledihairstudio.co.bw", type: "dtf_transfers", description: "Gold logo transfers for salon aprons", qty: 30, route: ["admin", "dtf", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: 40, priority: "standard", total: 1050, deposit: 1050, fulfilment: "collection", delivery: "not_started", notes: "Keep transfers flat; customer will heat press.", done: 1, working: false },
  { id: "JC-2609-161", odooRef: "SO-2026-1042", odooSynced: true, customer: "Mogoditshane Junior School", contact: "+267 71384529", email: "admin@mogoditshanejunior.ac.bw", type: "flyer_design", description: "A5 open day flyer", qty: 200, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "pending", revisionsUsed: 1, dueInHours: 30, priority: "standard", total: 850, deposit: 425, fulfilment: "collection", delivery: "not_started", notes: "Use school colours and include map QR code.", done: 2, working: false },
  { id: "JC-2609-166", odooRef: "SO-2026-1047", odooSynced: true, customer: "Tsholofelo Hair Studio", contact: "+267 74219063", email: "bookings@tsholofelohair.co.bw", type: "flyer_design", description: "A6 salon promo flyer", qty: 500, route: ["admin", "design", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: -6, priority: "standard", total: 980, deposit: 0, fulfilment: "delivery", address: "Plot 54368, CBD, Gaborone", delivery: "packed", notes: "Client waiting for lunch-hour handout.", done: 3, working: false },
  { id: "JC-2609-173", odooRef: "SO-2026-1051", odooSynced: true, customer: "Extension Gunners Supporters Club", contact: "+267 76831204", email: "supporters@extensiongunners.co.bw", type: "flyer_design", description: "A5 match day flyer", qty: 300, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "changes_requested", revisionsUsed: 2, dueInHours: 18, priority: "rush", total: 1250, deposit: 625, fulfilment: "delivery", address: "Molepolole Road, Block 6, Gaborone", delivery: "not_started", notes: "Update fixture time before final export.", done: 1, working: true },
  { id: "JC-2609-179", odooRef: "SO-2026-1058", odooSynced: true, customer: "Naledi Funeral Parlour", contact: "+267 72160488", email: "orders@naledifuneral.co.bw", type: "flyer_design", description: "A4 memorial service flyer", qty: 100, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 72, priority: "standard", total: 780, deposit: 780, fulfilment: "collection", delivery: "not_started", notes: "Approved by family representative.", done: 1, working: false },
  { id: "JC-2609-141", odooRef: "SO-2026-1038", odooSynced: true, customer: "Maruapula School", contact: "+267 39123456", email: "orders@maruapulaschool.co.bw", type: "print_press", description: "A5 colour flyers for open day", qty: 500, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 30, priority: "standard", total: 1750, deposit: 875, fulfilment: "delivery", address: "Plot 2786, Extension 12, Gaborone", delivery: "not_started", notes: "Print after final principal sign-off.", done: 1, working: true },
  { id: "JC-2609-146", odooRef: "SO-2026-1041", odooSynced: true, customer: "Mogoditshane Taxi Association", contact: "+267 71349820", email: "admin@mogoditshanetaxi.co.bw", type: "print_press", description: "A3 route fare posters", qty: 80, route: ["admin", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: -6, priority: "rush", total: 960, deposit: 0, fulfilment: "collection", delivery: "not_started", notes: "Overdue; customer wants first batch today.", done: 1, working: false },
  { id: "JC-2609-153", odooRef: "SO-2026-1047", odooSynced: true, customer: "Tlotlo Funeral Parlour", contact: "+267 74220918", email: "bookings@tlotlofunerals.co.bw", type: "print_press", description: "A4 funeral programmes", qty: 150, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "pending", revisionsUsed: 2, dueInHours: 18, priority: "rush", total: 2250, deposit: 1125, fulfilment: "delivery", address: "Block 8, Gaborone", delivery: "not_started", notes: "Awaiting hymn order confirmation.", done: 2, working: false },
  { id: "JC-2609-159", odooRef: "SO-2026-1052", odooSynced: true, customer: "Phakalane Beauty Salon", contact: "+267 76884503", email: "hello@phakalanebeautysalon.co.bw", type: "print_press", description: "DL price list brochures", qty: 250, route: ["admin", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: 72, priority: "standard", total: 1375, deposit: 1375, fulfilment: "collection", delivery: "not_started", notes: "Use 170gsm gloss paper.", done: 1, working: false },
  { id: "JC-2609-101", odooRef: "SO-2026-1001", odooSynced: true, customer: "Mogoditshane Junior School", contact: "+267 71324567", email: "admin@mogoditshanejuniorschool.co.bw", type: "stickers", description: "vinyl merit badge stickers", qty: 300, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "approved", revisionsUsed: 1, dueInHours: 28, priority: "standard", total: 1350, deposit: 675, fulfilment: "collection", delivery: "not_started", notes: "Cut into sheets of 20 for easy issuing.", done: 1, working: false },
  { id: "JC-2609-104", odooRef: "SO-2026-1002", odooSynced: true, customer: "Phakalane Grace Church", contact: "+267 74219855", email: "orders@phakalanegracechurch.org", type: "stickers", description: "round event logo stickers", qty: 200, route: ["admin", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: -6, priority: "standard", total: 900, deposit: 900, fulfilment: "delivery", address: "Plot 61071, Phakalane, Gaborone", delivery: "packed", notes: "Customer called twice; deliver before evening service.", done: 2, working: false },
  { id: "JC-2609-109", odooRef: "SO-2026-1003", odooSynced: true, customer: "Tsholofelo Hair & Beauty Salon", contact: "+267 76553018", email: "bookings@tsholofelohairbeauty.co.bw", type: "stickers", description: "product jar label stickers", qty: 120, route: ["admin", "design", "accounts"], artwork: "in_house", approval: "pending", revisionsUsed: 2, dueInHours: 52, priority: "standard", total: 780, deposit: 390, fulfilment: "collection", delivery: "not_started", notes: "Awaiting final scent names for three labels.", done: 2, working: false },
  { id: "JC-2609-116", odooRef: "SO-2026-1004", odooSynced: true, customer: "Kgale View Tuckshop", contact: "+267 72100492", email: "kgaleviewtuckshop@gmail.com", type: "stickers", description: "price promo window stickers", qty: 60, route: ["admin", "accounts"], artwork: "client_supplied", approval: "not_required", revisionsUsed: 0, dueInHours: 12, priority: "rush", total: 660, deposit: 0, fulfilment: "delivery", address: "Kgale View Mall, Gaborone", delivery: "not_started", notes: "Use removable vinyl; owner wants no residue.", done: 1, working: true },
];

const HOUR = 3_600_000;
const STAFF: Record<string, string[]> = {
  admin: ["Boitumelo", "Refilwe"], design: ["Tebogo", "Amantle"], sublimation: ["Kabo"],
  dtf: ["Onneile", "Gape"], sewing: ["Mpho", "Lesego"], embroidery: ["Neo"], accounts: ["Keneilwe"],
};

/** Fresh copy of the sample day, always relative to right now. */
export function SEED(): Order[] {
  const now = Date.now();
  return RAW.map(r => {
    const { dueInHours, done, working, ...rest } = r;
    const stages: Stage[] = buildStages(r.route).map((s, i) => {
      const who = STAFF[s.dept]?.[i % (STAFF[s.dept]?.length || 1)] ?? "—";
      if (i < done) return { ...s, status: "done", assignee: who, finishedAt: now - (done - i) * 40 * 60_000 };
      if (i === done && working) return { ...s, status: "in_progress", assignee: who, startedAt: now - 35 * 60_000 };
      return s;
    });
    return {
      ...rest,
      stages,
      createdAt: now - (26 - Math.min(24, dueInHours + 24)) * HOUR,
      dueAt: now + dueInHours * HOUR,
    } as Order;
  });
}
